#!/usr/bin/env bash
# A throwaway ES256 keystore for the test run. It lives under target/, is regenerated by
# every clean build, and signs nothing that is valid anywhere else — which is why its
# password can sit in src/test/resources without being a secret.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=target/test-keys/pokedex-test.p12
[ -f "$OUT" ] && exit 0
mkdir -p "$(dirname "$OUT")"
keytool -genkeypair -alias pokedex-test -keyalg EC -groupname secp256r1 \
  -sigalg SHA256withECDSA -validity 3650 -storetype PKCS12 \
  -keystore "$OUT" -storepass test-keystore-not-a-secret \
  -dname "CN=pokedex-api-test, O=ElatusDev, C=US" >/dev/null
echo "generated $OUT"
