-- Copyright (c) 2026 ElatusDev
-- The relational model of docs/diagrams/entity-relationship.md.
--
-- CHECK constraints here mirror domain invariants that already hold in the aggregate; they
-- do not invent new ones. A rule enforced only in the database is a 500 waiting for the
-- first caller who does not go through the aggregate, and a rule enforced only in the
-- aggregate is one seed script away from being false.
--
-- There is no deleted_at. Deletes are hard (ADR-0010).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)  NOT NULL,
    email         VARCHAR(320) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    roles         VARCHAR(100) NOT NULL,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ux_users_username UNIQUE (username),
    CONSTRAINT ux_users_email UNIQUE (email),
    CONSTRAINT ck_users_roles_present CHECK (roles <> '')
);

CREATE TABLE pokemon (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poke_api_id             INTEGER,
    name                    VARCHAR(60)   NOT NULL,
    category                VARCHAR(60),
    mass_hectograms         INTEGER       NOT NULL,
    height_decimetres       INTEGER       NOT NULL,
    base_experience         INTEGER       NOT NULL,
    sprite_front_default    VARCHAR(500),
    sprite_official_artwork VARCHAR(500),
    description             VARCHAR(2000),
    region                  VARCHAR(20),
    notes                   VARCHAR(2000),
    replication_state       VARCHAR(20)   NOT NULL,
    curated_by              BIGINT,
    synced_at               TIMESTAMPTZ,
    version                 BIGINT        NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- the curator is a separate aggregate, referenced by id only. Deleting a user is not a
    -- reason to delete the records they curated, so this is the one FK that does not cascade.
    CONSTRAINT fk_pokemon_curated_by FOREIGN KEY (curated_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_pokemon_state CHECK (
        replication_state IN ('DRAFT', 'PENDING', 'SYNCED', 'CUSTOMIZED', 'STALE', 'FAILED')),
    -- F3 — mass and height are strictly positive, in upstream units (IA3)
    CONSTRAINT ck_pokemon_mass_positive CHECK (mass_hectograms > 0),
    CONSTRAINT ck_pokemon_height_positive CHECK (height_decimetres > 0),
    CONSTRAINT ck_pokemon_base_experience CHECK (base_experience >= 0),
    CONSTRAINT ck_pokemon_poke_api_id_positive CHECK (poke_api_id IS NULL OR poke_api_id > 0),
    -- F6 — DRAFT is exactly the set of unlinked records, in both directions
    CONSTRAINT ck_pokemon_draft_iff_unlinked CHECK (
        (replication_state = 'DRAFT') = (poke_api_id IS NULL)),
    -- F5 — any replicated state implies a sync timestamp
    CONSTRAINT ck_pokemon_synced_at_when_replicated CHECK (
        replication_state NOT IN ('SYNCED', 'CUSTOMIZED', 'STALE') OR synced_at IS NOT NULL)
);

-- I1/F1 — partial, and it has to be. A DRAFT record has no poke_api_id, and under a plain
-- unique constraint Postgres treats NULLs as distinct, so the constraint would hold but the
-- index would be carrying rows it can never constrain. The predicate says what is meant.
CREATE UNIQUE INDEX ux_pokemon_poke_api_id ON pokemon (poke_api_id) WHERE poke_api_id IS NOT NULL;

-- PokemonName equality is case-insensitive, so the lookup is too, and it needs an index that
-- matches. Not unique: only poke_api_id is (I1), and two hand-created drafts may share a name.
CREATE INDEX ix_pokemon_lower_name ON pokemon (lower(name));
CREATE INDEX ix_pokemon_curated_by ON pokemon (curated_by);

CREATE TABLE pokemon_ability (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id BIGINT      NOT NULL,
    name       VARCHAR(60) NOT NULL,
    slot       INTEGER     NOT NULL,
    hidden     BOOLEAN     NOT NULL,
    CONSTRAINT fk_pokemon_ability_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE,
    CONSTRAINT ck_pokemon_ability_slot CHECK (slot > 0)
);
CREATE INDEX ix_pokemon_ability_pokemon ON pokemon_ability (pokemon_id);

CREATE TABLE pokemon_stat (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id BIGINT      NOT NULL,
    name       VARCHAR(60) NOT NULL,
    base_value INTEGER     NOT NULL,
    effort     INTEGER     NOT NULL,
    CONSTRAINT fk_pokemon_stat_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE,
    CONSTRAINT ck_pokemon_stat_base_value CHECK (base_value >= 0),
    CONSTRAINT ck_pokemon_stat_effort CHECK (effort >= 0)
);
CREATE INDEX ix_pokemon_stat_pokemon ON pokemon_stat (pokemon_id);

CREATE TABLE pokemon_type (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id BIGINT      NOT NULL,
    name       VARCHAR(60) NOT NULL,
    slot       INTEGER     NOT NULL,
    CONSTRAINT fk_pokemon_type_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE,
    CONSTRAINT ck_pokemon_type_slot CHECK (slot > 0)
);
CREATE INDEX ix_pokemon_type_pokemon ON pokemon_type (pokemon_id);

CREATE TABLE pokemon_tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id BIGINT      NOT NULL,
    label      VARCHAR(30) NOT NULL,
    CONSTRAINT fk_pokemon_tag_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE
);
-- F4 — case-insensitively distinct within a Pokemon. Pokemon.addTag already rejects a
-- duplicate; this is the same rule for anything that reaches the table another way.
CREATE UNIQUE INDEX ux_pokemon_tag_label ON pokemon_tag (pokemon_id, lower(label));

CREATE TABLE localized_name (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id BIGINT       NOT NULL,
    locale     VARCHAR(20)  NOT NULL,
    value      VARCHAR(120) NOT NULL,
    -- the discriminator the whole merge policy turns on: re-sync replaces UPSTREAM rows and
    -- must not touch CURATOR rows (F7)
    source     VARCHAR(10)  NOT NULL,
    CONSTRAINT fk_localized_name_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE,
    CONSTRAINT ck_localized_name_source CHECK (source IN ('UPSTREAM', 'CURATOR'))
);
CREATE INDEX ix_localized_name_pokemon ON localized_name (pokemon_id, source);

CREATE TABLE evolution_link (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id        BIGINT      NOT NULL,
    from_poke_api_id  INTEGER     NOT NULL,
    to_poke_api_id    INTEGER     NOT NULL,
    evolution_trigger VARCHAR(60) NOT NULL,
    min_level         INTEGER,
    CONSTRAINT fk_evolution_link_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE,
    CONSTRAINT ck_evolution_link_endpoints CHECK (from_poke_api_id > 0 AND to_poke_api_id > 0),
    -- the weakest form of F12: a self-loop is a cycle the flattener can produce on its own
    CONSTRAINT ck_evolution_link_distinct CHECK (from_poke_api_id <> to_poke_api_id),
    CONSTRAINT ck_evolution_link_min_level CHECK (min_level IS NULL OR min_level > 0)
);
CREATE INDEX ix_evolution_link_pokemon ON evolution_link (pokemon_id);

-- Owned by WF-AUTH. The table is here because db/migration has a single writer and a second
-- one would produce two V2s; the entity and the rotation logic belong to WU-AUTH-A.
CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    family_id  VARCHAR(64) NOT NULL,
    jti        VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ux_refresh_tokens_jti UNIQUE (jti)
);
-- I8/F11 asks "is there another live token in this family?", which is this index
CREATE INDEX ix_refresh_tokens_family ON refresh_tokens (user_id, family_id);
